### ISSUE TITLE
is https://howsmyssl.com/ site hacked?

### ISSUE THREAD

**Issue by venki-thiyag** [zeke/electron-electron-issues#1]
Receiving insecure connection error when tls.py script is executed. is https://howsmyssl.com/ site hacked and certificate provided by that domain seems to be invalid.

**Comment by shiftkey** [comment]
@venki-thiyag I don't think this is the right repository to help understand the issue, and `howsmyssl.com` seems to be rendering fine for me on a recent version of Chrome:

<img width="1002"  src="https://user-images.githubusercontent.com/359239/42390620-e4e69232-8122-11e8-8350-9f6f81bf039c.png">
